--- #YAML:1.0
name: Tk-AbstractCanvas
abstract: Canvas with Abstract center, zoom, && rotate methods
version: 1.4.A7QFZHF
author:
  - Pip Stuart <Pip@CPAN.Org>
license: gpl
distribution_type: module
requires:
  Tk: 0
  Tk::Canvas: 0
  Tk::Derived: 0
recommends:
build_requires:
  Test: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
urls:
  license: HTTP://FSF.Org/licensing/licenses/gpl.txt
meta-spec:
  version: 1.3
  url: HTTP://Module-Build.SourceForge.Net/META-spec-v1.3.html
generated_by: e pkg v1.0.A2RJrKV
